services:
  php_run:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app

    working_dir: /app
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: postgresql://app:password@database:5432/ux_components?serverVersion=16&charset=utf8
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app

    working_dir: /app/demo
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: postgresql://app:password@database:5432/ux_components?serverVersion=16&charset=utf8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - .:/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ux_components
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}" ]
      interval: 5s
      timeout: 5s
      retries: 20
